-- Add contact page translations
INSERT INTO ui_strings (key, category, text_uk, text_ru, text_pl, text_en) VALUES
('pages.contacts.info.title', 'contact', 'Контактна інформація', 'Контактная информация', 'Informacje kontaktowe', 'Contact Information'),
('pages.contacts.info.phone_desc', 'contact', 'Доступний щодня з 10:00 до 22:00', 'Доступен ежедневно с 10:00 до 22:00', 'Dostępny codziennie od 10:00 do 22:00', 'Available daily from 10:00 to 22:00'),
('pages.contacts.info.email_desc', 'contact', 'Відповімо протягом 24 годин', 'Ответим в течение 24 часов', 'Odpowiemy w ciągu 24 godzin', 'We will respond within 24 hours'),
('pages.contacts.info.location_value', 'contact', 'Вроцлав, Польща', 'Вроцлав, Польша', 'Wrocław, Polska', 'Wrocław, Poland'),
('pages.contacts.info.location_desc', 'contact', 'Основна база операцій', 'Основная база операций', 'Główna baza operacyjna', 'Main base of operations'),
('pages.contacts.info.hours_value', 'contact', 'Пн-Нд: 10:00 - 22:00', 'Пн-Вс: 10:00 - 22:00', 'Pn-Nd: 10:00 - 22:00', 'Mon-Sun: 10:00 - 22:00'),
('pages.contacts.info.hours_desc', 'contact', 'Час для зв''язку та консультацій', 'Время для связи и консультаций', 'Czas na kontakt i konsultacje', 'Time for contact and consultations'),
('pages.contacts.social.title', 'contact', 'Соціальні мережі', 'Социальные сети', 'Media społecznościowe', 'Social Media'),
('pages.contacts.actions.title', 'contact', 'Швидкі дії', 'Быстрые действия', 'Szybkie akcje', 'Quick Actions'),
('pages.contacts.actions.telegram', 'contact', 'Написати в Telegram', 'Написать в Telegram', 'Napisać na Telegram', 'Write to Telegram'),
('pages.contacts.actions.callback', 'contact', 'Замовити дзвінок', 'Заказать звонок', 'Zamówić rozmowę', 'Request a call'),
('pages.contacts.form.title', 'contact', 'Зв''язатися з нами', 'Связаться с нами', 'Skontaktuj się z nami', 'Contact Us'),
('pages.contacts.form.description', 'contact', 'Заповніть форму, і ми зв''яжемося з вами найближчим часом', 'Заполните форму, и мы свяжемся с вами в ближайшее время', 'Wypełnij formularz, a skontaktujemy się z Tobą w najbliższym czasie', 'Fill out the form and we will contact you shortly'),
('pages.contacts.form.name_placeholder', 'contact', 'Ваше ім''я', 'Ваше имя', 'Twoje imię', 'Your name'),
('pages.contacts.form.phone_placeholder', 'contact', '+48 123 456 789', '+48 123 456 789', '+48 123 456 789', '+48 123 456 789'),
('pages.contacts.form.email_placeholder', 'contact', 'your.email@example.com', 'your.email@example.com', 'your.email@example.com', 'your.email@example.com'),
('pages.contacts.form.subject', 'contact', 'Тема повідомлення', 'Тема сообщения', 'Temat wiadomości', 'Message Subject'),
('pages.contacts.form.subject_placeholder', 'contact', 'Про що хочете поговорити?', 'О чем хотите поговорить?', 'O czym chcesz porozmawiać?', 'What would you like to talk about?'),
('pages.contacts.form.message_placeholder', 'contact', 'Розкажіть детальніше про своє питання або пропозицію...', 'Расскажите подробнее о своем вопросе или предложении...', 'Opowiedz więcej o swoim pytaniu lub propozycji...', 'Tell us more about your question or suggestion...'),
('pages.contacts.form.privacy', 'contact', 'Надсилаючи форму, ви погоджуєтесь з обробкою особистих даних', 'Отправляя форму, вы соглашаетесь с обробкой персональных данных', 'Wysyłając formularz, zgadzasz się na przetwarzanie danych osobowych', 'By submitting the form, you agree to the processing of personal data'),
('pages.contacts.faq.title', 'contact', 'Часто задавані питання', 'Часто задаваемые вопросы', 'Często zadawane pytania', 'Frequently Asked Questions'),
('pages.contacts.faq.join.question', 'contact', 'Як приєднатися до команди?', 'Как присоединиться к команде?', 'Jak dołączyć do zespołu?', 'How to join the team?'),
('pages.contacts.faq.join.answer', 'contact', 'Зв''яжіться з нами будь-яким зручним способом. Ми розповімо про вимоги, запросимо на тренування та допоможемо з вибором спорядження.', 'Свяжитесь с нами любым удобным способом. Мы расскажем о требованиях, пригласим на тренировку и поможем с выбором снаряжения.', 'Skontaktuj się z nami w dowolny wygodny sposób. Opowiemy o wymaganiach, zaprosimy na trening i pomożemy w wyborze sprzętu.', 'Contact us in any convenient way. We will tell you about the requirements, invite you to training and help you choose equipment.'),
('pages.contacts.faq.equipment.question', 'contact', 'Чи потрібне власне спорядження?', 'Нужно ли свое снаряжение?', 'Czy potrzebny jest własny sprzęt?', 'Do I need my own equipment?'),
('pages.contacts.faq.equipment.answer', 'contact', 'Для початку можна використовувати орендоване спорядження. Допоможемо з вибором та покупкою власного обладнання.', 'Для начала можно использовать арендованное снаряжение. Поможем с выбором и покупкой собственного оборудования.', 'Na początek można używać wypożyczonego sprzętu. Pomożemy w wyborze i zakupie własnego wyposażenia.', 'You can start with rented equipment. We will help you choose and buy your own equipment.'),
('pages.contacts.faq.level.question', 'contact', 'Який рівень підготовки потрібен?', 'Какой уровень подготовки нужен?', 'Jaki poziom przygotowania jest potrzebny?', 'What level of preparation is needed?'),
('pages.contacts.faq.level.answer', 'contact', 'Приймаємо гравців будь-якого рівня. Головне - бажання вчитися, дисциплінованість та командний дух.', 'Принимаем игроков любого уровня. Главное - желание учиться, дисциплинированность и командный дух.', 'Przyjmujemy graczy każdego poziomu. Najważniejsze to chęć nauki, dyscyplina i duch zespołowy.', 'We accept players of any level. The main thing is the desire to learn, discipline and team spirit.'),
('pages.contacts.faq.frequency.question', 'contact', 'Як часто проводяться ігри?', 'Как часто проводятся игры?', 'Jak często odbywają się gry?', 'How often are games held?'),
('pages.contacts.faq.frequency.answer', 'contact', 'Організовуємо ігри 2-3 рази на місяць. Також беремо участь у турнірах та спеціальних заходах по всій Польщі.', 'Организуем игры 2-3 раза в месяц. Также участвуем в турнирах и специальных мероприятиях по всей Польше.', 'Organizujemy gry 2-3 razy w miesiącu. Bierzemy też udział w turniejach i specjalnych wydarzeniach w całej Polsce.', 'We organize games 2-3 times a month. We also participate in tournaments and special events throughout Poland.')
ON CONFLICT (key) DO UPDATE SET
  text_uk = EXCLUDED.text_uk,
  text_ru = EXCLUDED.text_ru,
  text_pl = EXCLUDED.text_pl,
  text_en = EXCLUDED.text_en,
  updated_at = now();