-- First ensure key column is unique and then insert translations
CREATE UNIQUE INDEX IF NOT EXISTS ui_strings_key_unique ON ui_strings (key);

-- Insert all static translations from translations.ts into ui_strings table
INSERT INTO ui_strings (key, category, text_uk, text_ru, text_pl, text_en) VALUES
('nav.games', 'navigation', 'Ігри', 'Игры', 'Gry', 'Games'),
('nav.team', 'navigation', 'Команда', 'Команда', 'Zespół', 'Team'),
('nav.gallery', 'navigation', 'Галерея', 'Галерея', 'Galeria', 'Gallery'),
('nav.articles', 'navigation', 'Статті', 'Статьи', 'Artykuły', 'Articles'),
('nav.contacts', 'navigation', 'Контакти', 'Контакты', 'Kontakt', 'Contacts'),
('nav.about', 'navigation', 'Про нас', 'О нас', 'O nas', 'About'),
('nav.search', 'navigation', 'Пошук', 'Поиск', 'Szukaj', 'Search'),
('nav.subscribe', 'navigation', 'Підписка', 'Подписка', 'Subskrypcja', 'Subscribe'),
('common.readMore', 'common', 'Читати далі', 'Читать далее', 'Czytaj więcej', 'Read More'),
('common.loadMore', 'common', 'Завантажити ще', 'Загрузить еще', 'Załaduj więcej', 'Load More'),
('common.loading', 'common', 'Завантаження...', 'Загрузка...', 'Ładowanie...', 'Loading...'),
('common.error', 'common', 'Помилка', 'Ошибка', 'Błąd', 'Error'),
('common.notFound', 'common', 'Не знайдено', 'Не найдено', 'Nie znaleziono', 'Not Found'),
('common.back', 'common', 'Назад', 'Назад', 'Wstecz', 'Back'),
('common.next', 'common', 'Далі', 'Далее', 'Dalej', 'Next'),
('common.previous', 'common', 'Попередній', 'Предыдущий', 'Poprzedni', 'Previous'),
('common.home', 'common', 'Головна', 'Главная', 'Strona główna', 'Home'),
('common.register', 'common', 'Реєстрація', 'Регистрация', 'Rejestracja', 'Register'),
('common.subscribe', 'common', 'Підписатися', 'Подписаться', 'Subskrybuj', 'Subscribe'),
('common.submit', 'common', 'Відправити', 'Отправить', 'Wyślij', 'Submit'),
('common.cancel', 'common', 'Скасувати', 'Отменить', 'Anuluj', 'Cancel'),
('common.save', 'common', 'Зберегти', 'Сохранить', 'Zapisz', 'Save'),
('common.edit', 'common', 'Редагувати', 'Редактировать', 'Edytuj', 'Edit'),
('common.delete', 'common', 'Видалити', 'Удалить', 'Usuń', 'Delete'),
('common.view', 'common', 'Переглянути', 'Просмотреть', 'Zobacz', 'View'),
('common.share', 'common', 'Поділитися', 'Поделиться', 'Udostępnij', 'Share'),
('common.download', 'common', 'Завантажити', 'Скачать', 'Pobierz', 'Download'),
('common.success', 'common', 'Успіх', 'Успех', 'Sukces', 'Success'),
('common.event', 'common', 'Подія', 'Событие', 'Wydarzenie', 'Event'),
('common.article', 'common', 'Стаття', 'Статья', 'Artykuł', 'Article'),
('common.category', 'common', 'Категорія', 'Категория', 'Kategoria', 'Category'),
('common.test', 'common', 'Тест', 'Тест', 'Test', 'Test'),
('hero.title', 'hero', 'RAVEN STRIKE FORCE', 'RAVEN STRIKE FORCE', 'RAVEN STRIKE FORCE', 'RAVEN STRIKE FORCE'),
('hero.subtitle', 'hero', 'ПРОФЕСІЙНИЙ СТРАЙКБОЛ У ВРОЦЛАВІ', 'ПРОФЕССИОНАЛЬНЫЙ СТРАЙКБОЛ ВО ВРОЦЛАВЕ', 'PROFESJONALNY AIRSOFT WE WROCŁAWIU', 'PROFESSIONAL AIRSOFT IN WROCŁAW'),
('hero.cta', 'hero', 'Приєднатися до команди', 'Присоединиться к команде', 'Dołącz do zespołu', 'Join the Team'),
('hero.stats.players', 'hero', 'Гравців', 'Игроков', 'Graczy', 'Players'),
('hero.stats.gamesPerYear', 'hero', 'Ігор на рік', 'Игр в год', 'Gier rocznie', 'Games per Year'),
('hero.stats.yearsExperience', 'hero', 'Років досвіду', 'Лет опыта', 'Lat doświadczenia', 'Years of Experience'),
('admin.title', 'admin', 'Адміністрування', 'Администрирование', 'Panel administracyjny', 'Admin Panel'),
('admin.dashboard', 'admin', 'Панель керування', 'Панель управления', 'Panel sterowania', 'Dashboard'),
('admin.dashboardSubtitle', 'admin', 'Огляд статистики та швидкий доступ до управління', 'Обзор статистики и быстрый доступ к управлению', 'Przegląd statystyk i szybki dostęp do zarządzania', 'Manage site content and settings'),
('admin.articles', 'admin', 'Статті', 'Статьи', 'Artykuły', 'Articles'),
('admin.gallery', 'admin', 'Галерея', 'Галерея', 'Galeria', 'Gallery'),
('admin.events', 'admin', 'Події', 'События', 'Wydarzenia', 'Events'),
('admin.team', 'admin', 'Команда', 'Команда', 'Zespół', 'Team'),
('admin.users', 'admin', 'Користувачі', 'Пользователи', 'Użytkownicy', 'Users'),
('admin.statistics', 'admin', 'Статистика', 'Статистика', 'Statystyki', 'Statistics'),
('admin.settings', 'admin', 'Налаштування', 'Настройки', 'Ustawienia', 'Settings'),
('admin.totalArticles', 'admin', 'Всього статей', 'Всего статей', 'Łącznie artykułów', 'Total Articles'),
('admin.totalUsers', 'admin', 'Всього користувачів', 'Всего пользователей', 'Łącznie użytkowników', 'Total Users'),
('admin.totalEvents', 'admin', 'Всього подій', 'Всего событий', 'Łącznie wydarzeń', 'Total Events'),
('admin.totalRegistrations', 'admin', 'Всього реєстрацій', 'Всего регистраций', 'Łącznie rejestracji', 'Total Registrations'),
('admin.galleryItems', 'admin', 'Елементів галереї', 'Элементов галереи', 'Elementów galerii', 'Gallery Items'),
('admin.teamMembers', 'admin', 'Учасників команди', 'Участников команды', 'Członków zespołu', 'Team Members'),
('admin.published', 'admin', 'Опубліковано', 'Опубликовано', 'Opublikowane', 'Published'),
('admin.drafts', 'admin', 'Чернетки', 'Черновики', 'Szkice', 'Drafts'),
('admin.admins', 'admin', 'адмінів', 'админов', 'adminów', 'Admins'),
('admin.editors', 'admin', 'редакторів', 'редакторов', 'redaktorów', 'Editors'),
('admin.upcoming', 'admin', 'майбутніх', 'предстоящих', 'nadchodzących', 'Upcoming'),
('admin.completed', 'admin', 'завершених', 'завершенных', 'zakończonych', 'Completed'),
('admin.eventRegistrations', 'admin', 'реєстрації на події', 'регистрации на события', 'rejestracje na wydarzenia', 'Event Registrations'),
('admin.photosAndVideos', 'admin', 'фото та відео', 'фото и видео', 'zdjęcia i filmy', 'Photos and Videos'),
('admin.activeMembers', 'admin', 'активних учасників', 'активных участников', 'aktywnych członków', 'Active Members'),
('admin.quickActions', 'admin', 'Швидкі дії', 'Быстрые действия', 'Szybkie akcje', 'Quick Actions'),
('admin.createArticle', 'admin', 'Створити статтю', 'Создать статью', 'Utwórz artykuł', 'Create Article'),
('admin.systemInfo', 'admin', 'Інформація про систему', 'Информация о системе', 'Informacje o systemie', 'System Info'),
('admin.databaseStatus', 'admin', 'Статус бази даних', 'Статус базы данных', 'Status bazy danych', 'Database Status'),
('admin.online', 'admin', 'Онлайн', 'Онлайн', 'Online', 'Online'),
('admin.lastBackup', 'admin', 'Останній бекап', 'Последний бекап', 'Ostatnia kopia zapasowa', 'Last Backup'),
('admin.automated', 'admin', 'Автоматично', 'Автоматически', 'Automatycznie', 'Automated'),
('admin.roles.title', 'admin', 'Управління ролями', 'Управление ролями', 'Zarządzanie rolami', 'Role Management'),
('admin.roles.description', 'admin', 'Призначення ролей користувачам', 'Назначение ролей пользователям', 'Przypisywanie ról użytkownikom', 'Assign roles to users'),
('admin.branding.title', 'admin', 'Управління брендом', 'Управление брендом', 'Zarządzanie marką', 'Brand Management'),
('admin.branding.description', 'admin', 'Налаштування брендингу та зовнішнього вигляду сайту', 'Настройка брендинга и внешнего вида сайта', 'Dostosowywanie brandingu i wyglądu strony', 'Customize site branding and appearance'),
('admin.articles.title', 'admin', 'Статті', 'Статьи', 'Artykuły', 'Articles'),
('admin.articles.description', 'admin', 'Створення та редагування статей', 'Создание и редактирование статей', 'Tworzenie i edytowanie artykułów', 'Create and edit articles'),
('auth.login', 'auth', 'Увійти', 'Войти', 'Zaloguj', 'Login'),
('auth.logout', 'auth', 'Вийти', 'Выйти', 'Wyloguj', 'Logout'),
('auth.pleaseLogin', 'auth', 'Будь ласка, увійдіть до системи', 'Пожалуйста, войдите в систему', 'Proszę się zalogować', 'Please log in to continue'),
('pages.games.title', 'pages', 'Найближчі ігри', 'Ближайшие игры', 'Nadchodzące gry', 'Upcoming Games'),
('pages.games.subtitle', 'pages', 'Календар страйкбольних подій та сценаріїв', 'Календарь страйкбольных событий и сценариев', 'Kalendarz wydarzeń airsoftowych i scenariuszy', 'Calendar of airsoft events and scenarios'),
('pages.games.noGames', 'pages', 'Наразі немає запланованих ігор', 'Пока нет запланированных игр', 'Obecnie brak zaplanowanych gier', 'No games scheduled'),
('pages.team.title', 'pages', 'Наша команда', 'Наша команда', 'Nasz zespół', 'Our Team'),
('pages.team.subtitle', 'pages', 'Професійні гравці Raven Strike Force', 'Профессиональные игроки Raven Strike Force', 'Profesjonalni gracze Raven Strike Force', 'Meet the Raven Strike Force members'),
('pages.team.noMembers', 'pages', 'Інформація про команду недоступна', 'Информация о команде недоступна', 'Informacje o zespole niedostępne', 'No team members found'),
('pages.gallery.title', 'pages', 'Галерея', 'Галерея', 'Galeria', 'Gallery'),
('pages.gallery.subtitle', 'pages', 'Фото та відео з наших ігор', 'Фото и видео с наших игр', 'Zdjęcia i filmy z naszych gier', 'Photos and videos from our games'),
('pages.gallery.noMedia', 'pages', 'Немає медіафайлів', 'Нет медиафайлов', 'Brak plików multimedialnych', 'No media files found'),
('pages.articles.title', 'pages', 'Статті', 'Статьи', 'Artykuły', 'Articles'),
('pages.articles.subtitle', 'pages', 'Поради, гайди та новини зі світу страйкболу', 'Советы, гайды и новости из мира страйкбола', 'Porady, przewodniki i wiadomości ze świata airsoftu', 'Guides, news, and tactical materials'),
('pages.articles.noArticles', 'pages', 'Статті не знайдені', 'Статьи не найдены', 'Nie znaleziono artykułów', 'No articles found'),
('pages.contacts.title', 'pages', 'Контакти', 'Контакты', 'Kontakt', 'Contacts'),
('pages.contacts.subtitle', 'pages', 'Звяжіться з нами для участі в іграх', 'Свяжитесь с нами для участия в играх', 'Skontaktuj się z nami', 'Get in touch with us'),
('pages.contacts.form.name', 'pages', 'Імя', 'Имя', 'Imię', 'Name'),
('pages.contacts.form.email', 'pages', 'Email', 'Email', 'Email', 'Email'),
('pages.contacts.form.phone', 'pages', 'Телефон', 'Телефон', 'Telefon', 'Phone'),
('pages.contacts.form.message', 'pages', 'Повідомлення', 'Сообщение', 'Wiadomość', 'Message'),
('pages.contacts.form.submit', 'pages', 'Відправити', 'Отправить', 'Wyślij', 'Send Message'),
('pages.contacts.form.success', 'pages', 'Повідомлення відправлено успішно!', 'Сообщение отправлено успешно!', 'Wiadomość została wysłana pomyślnie!', 'Message sent successfully'),
('pages.contacts.form.error', 'pages', 'Помилка відправки повідомлення', 'Ошибка отправки сообщения', 'Błąd podczas wysyłania wiadomości', 'Error sending message'),
('pages.about.title', 'pages', 'Про Raven Strike Force', 'О Raven Strike Force', 'O Raven Strike Force', 'About Us'),
('pages.about.subtitle', 'pages', 'Наша місія та історія', 'Наша миссия и история', 'Nasza misja i historia', 'Our mission and values'),
('errors.insufficientPermissions', 'errors', 'Недостатньо прав доступу', 'Недостаточно прав доступа', 'Niewystarczające uprawnienia', 'Insufficient permissions'),
('errors.adminAccessRequired', 'errors', 'Потрібен доступ адміністратора або редактора', 'Требуется доступ администратора или редактора', 'Wymagany dostęp administratora lub redaktora', 'Admin or Editor access required'),
('categories.tactics', 'categories', 'Тактика', 'Тактика', 'Taktyka', 'Tactics'),
('categories.equipment', 'categories', 'Спорядження', 'Снаряжение', 'Sprzęt', 'Equipment'),
('categories.news', 'categories', 'Новини', 'Новости', 'Wiadomości', 'News'),
('categories.gameReports', 'categories', 'Звіти з ігор', 'Отчеты с игр', 'Raporty z gier', 'Game Reports'),
('categories.rules', 'categories', 'Правила', 'Правила', 'Zasady', 'Rules'),
('admin.translations.title', 'admin', 'Переклади', 'Переводы', 'Tłumaczenia', 'Translations'),
('admin.translations.description', 'admin', 'Управління перекладами сайту', 'Управление переводами сайта', 'Zarządzanie tłumaczeniami strony', 'Manage site translations'),
('admin.translations.exportJson', 'admin', 'Експорт JSON', 'Экспорт JSON', 'Eksport JSON', 'Export JSON'),
('admin.translations.importJson', 'admin', 'Імпорт JSON', 'Импорт JSON', 'Import JSON', 'Import JSON'),
('admin.translations.searchPlaceholder', 'admin', 'Пошук перекладів...', 'Поиск переводов...', 'Szukaj tłumaczeń...', 'Search translations...'),
('admin.translations.category', 'admin', 'Категорія', 'Категория', 'Kategoria', 'Category'),
('admin.translations.key', 'admin', 'Ключ', 'Ключ', 'Klucz', 'Key'),
('admin.translations.missingTranslations', 'admin', 'Відсутні переклади', 'Отсутствующие переводы', 'Brakujące tłumaczenia', 'Missing translations'),
('admin.translations.addTranslation', 'admin', 'Додати переклад', 'Добавить перевод', 'Dodaj tłumaczenie', 'Add Translation'),
('admin.translations.saveSuccess', 'admin', 'Переклад збережено успішно', 'Перевод сохранен успешно', 'Tłumaczenie zapisane pomyślnie', 'Translation saved successfully'),
('admin.translations.importSuccess', 'admin', 'Переклади імпортовано успішно', 'Переводы импортированы успешно', 'Tłumaczenia zaimportowane pomyślnie', 'Translations imported successfully')
ON CONFLICT (key) DO UPDATE SET
  text_uk = EXCLUDED.text_uk,
  text_ru = EXCLUDED.text_ru,
  text_pl = EXCLUDED.text_pl,
  text_en = EXCLUDED.text_en,
  category = EXCLUDED.category,
  updated_at = now();