// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://oywbldhpmpjvavtcknvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95d2JsZGhwbXBqdmF2dGNrbnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTM3NzksImV4cCI6MjA3NDA2OTc3OX0.QncRqiykORnghbZYJSMr8q6vsnZ88H3GoLnwiq08GVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});